### ISSUE TITLE
Add support for twitter quick-replies buttons

### ISSUE THREAD

**Issue by jdwuarin** [botmasterai/botmaster-twitter-dm#1]
Do so as soon as quick-replies are out of beta in twitter DMs.

bot.sendDefaultButtonMessageTo should then create those in Twitter DMs

**Comment by bobber205** [comment]
This has been deprecated by Twitter 
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html

```
Some less-used features of the Direct Message beta will not become generally available and will no longer be functional from February 15, 2018. These features are:

    Location quick replies and location cards
    Text Input quick replies
```

**Comment by jdwuarin** [comment]
Thanks for the link. From looking at the link, it looks like they've come out of beta a while back. I don't have much time right now, so won't be able to implement this as fast as I would want to. But if anyone wants to give it a go, I'd be happy to review pull requests.

**Comment by abhishekchotaliya** [comment]
Hi John,
Thanks for this awesome project! 🤟🏻

Can you please tell me what is the flow of the framework? I understood most of the flow, but I am unable to figure out when you are converting the raw message to a platform-specific message.

**Comment by jdwuarin** [comment]
Hi @abhishekchotaliya. Following your pull requests on both this project and the botmaster on:
(this project: https://github.com/botmasterai/botmaster-twitter-dm/pull/3)
(the botmaster project: https://github.com/botmasterai/botmaster/pull/43)

Here's a few comments to help you get on with that. Changes like the ones you require should never require you change the base project (`botmaster`) and you should be able to edit the bot class project directly. In this case, botmaster-twitter-dm. You can read more on how you would go about creating a new bot class here:

http://botmasterai.com/documentation/latest/working-with-botmaster/writing-your-own-bot-class.html

You can start directly at the `Creating your own bot classes` section.

Hope that helped

**Comment by jdwuarin** [comment]
Closing issue as merge request #3 fixes this.
Version `1.1.0` has been released as a result
